AWSTemplateFormatVersion: "2010-09-09"
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  TortugaLive:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvents:
          Type: Api
          Properties:
            Path: /events
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /events
            Method: post
        GetEvent:
          Type: Api
          Properties:
            Path: /events/{event}
            Method: get
        DeleteEvent:
          Type: Api
          Properties:
            Path: /events/{event}
            Method: delete
        PutEvent:
          Type: Api
          Properties:
            Path: /events/{event}
            Method: put

  BrandoCFRolePolicy: 
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Join [ "-", [ !Ref ProjectId, "cf" ] ]
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action:
              - "iam:DeleteRolePolicy"
              - "iam:PutRolePolicy"
            Resource:
              - "*"
      Roles: 
        - !Join [ "-", [ 'CodeStarWorker', !Ref ProjectId, "CloudFormation" ] ]

  BrandoDynamoDBRolePolicy: 
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: !Join [ "-", [ !Ref ProjectId, "dynamodb" ] ]
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action:
              - "dynamodb:PutItem"
              - "dynamodb:GetItem"
              - "dynamodb:Query"
              - "dynamodb:Scan"
              - "dynamodb:DescribeTable"
            Resource: 
              - !GetAtt BrandoDynamoDBTable.Arn
      Roles: 
        - !Join [ "-", [ 'CodeStarWorker', !Ref ProjectId, "Lambda" ] ]

  BrandoDynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "ID"
          AttributeType: "S"
        - 
          AttributeName: "StartDate"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "ID"
          KeyType: "HASH"
        - 
          AttributeName: "StartDate"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "BrandoTable"
